[buildpack]
id = "com.orange.buildpacks.sidecars"
version = "__VERSION__"
name = "Sidecars buildpack"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
